# Generated by Django 3.0.5 on 2020-05-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20200506_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario_comentaio',
            new_name='usuario_comentario',
        ),
    ]
